
""" Lista de monedas

Define las monedas que se pueden seleccionar en el menú desplegable
multimoneda.

La primera moneda establecida en la lista será también la moneda
principal de la base de datos. Si necesita cambiar la moneda principal, 
cambie el orden de los elementos.
"""
CURRENCIES = [
    'USD', # Moneda principal    
    'VES', # Moneda secundaria 

    # Se pueden añadir más monedas según sea necesario.
    # Por ejemplo, para añadir el euro bastaría con quitar el siguiente
    # comentario y asegurarse de que la moneda esté activada en la base de datos.

    # 'EUR',
]

MONETARY_KEYWORDS = [
    'price',
    'amount',
    'total',
    'tax',
    'subtotal',
    'cost',
    'fee',
]

# Idioma para las etiquetas de los campos generados
LANG = 'es_ES'

AUTOGENERATED_WARNING = [
    "# ----------------------------------------------------------------------------",
    "# ** ATENCIÓN **",
    "# ---------------//",
    "# Este archivo ha sido generado automáticamente. Los cambios manuales serán",
    "# sobreescritos en el siguiente proceso de compilación.",
    "# ----------------------------------------------------------------------------",
]

LICENSE = [
    "Odoo Proprietary License v1.0",
    "Copyright (C) 2021 Soluciones DIMAC 21, C.A.",
    "",
    "This software and associated files (the “Software”) may only be used (executed, ",
    "modified, executed after modifications) if you have purchased a valid license ",
    "from the authors, typically via Odoo Apps, or if you have received a written ",
    "agreement from the authors of the Software (see the COPYRIGHT file).",
    "",
    "You may develop Odoo modules that use the Software as a library (typically by ",
    "depending on it, importing it and using its resources), but without copying any ",
    "source code or material from the Software. You may distribute those modules ",
    "under the license of your choice, provided that this license is compatible with ",
    "the terms of the Odoo Proprietary License (For example: LGPL, MIT, or ",
    "proprietary licenses similar to this one).",
    "",
    "It is forbidden to publish, distribute, sublicense, or sell copies of the ",
    "Software or modified copies of the Software.",
    "",
    "The above copyright notice and this permission notice must be included in all ",
    "copies or substantial portions of the Software.",
    "",
    "THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR ",
    "IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, ",
    "FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE ",
    "AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER ",
    "LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, ",
    "OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE ",
    "SOFTWARE.",
]

COPYRIGHT = [
    "Most of the files in this software are:",
    "",
    "Copyright (c) 2021-2026 Soluciones DIMAC 21, C.A.",
    "",
    "and are published under the Odoo Proprietary License v1.0 (OPL-1),",
    "as described in the LICENSE file.",
    "",
    "Some files may also contain contributions from third parties. In ",
    "this case, the original copyright of the contributions can be ",
    "traced through the history of the source version control system ",
    "(e.g., Git). When that is not the case, the files contain a prominent ",
    "notice stating the original copyright and applicable license, or come ",
    "with their own dedicated COPYRIGHT and/or LICENSE file.",
]