import os
import logging
from odoo import models, api
from odoo.modules.module import get_module_path
from odoo.addons.d21_multimoneda.config import (
    CURRENCIES, MONETARY_KEYWORDS, 
    AUTOGENERATED_WARNING, LICENSE, COPYRIGHT, 
    LANG, 
)

_logger = logging.getLogger(__name__)

class IrModuleModule(models.Model):
    _inherit = 'ir.module.module'   

    def instalar_modulos_multimoneda(self):
        """ Compila los módulos multimoneda y los instala/actualiza.
        
        @nota: Esta función es llamada desde el botón `Instalar módulos multimoneda` 
        del menú `Apps`"""

        self._compilar_modulos_multimoneda()
        self.update_list()

        # Buscar todos los módulos multimoneda
        modulos_multimoneda = self.search([('name', '=like', 'd21_multimoneda__%')])

        # Instalar solo aquellos módulos que tengan su dependencia principal instalada
        for modulo in modulos_multimoneda:
            dependencia = modulo.name.replace('d21_multimoneda__', '')
            if self.search([('name', '=', dependencia), ('state', 'in', ('installed', 'to upgrade'))]):
                modulo.button_immediate_install()

        return {
            'type': 'ir.actions.client',
            'tag': 'display_notification',
            'params': {
                'title': 'Módulos Multi-Moneda Instalados',
                'message': 'Los módulos multimoneda han sido instalados exitosamente.',
                'sticky': True,
                'type': 'success',
                'next': {'type': 'ir.actions.client', 'tag': 'reload'},
            }
        }

    def _compilar_modulos_multimoneda(self):
        """ Compila los módulos multimoneda """

        # 1. Determine paths
        try:
            base_module_path = get_module_path('d21_multimoneda')
        except:
            # Fallback if get_module_path fails
            base_module_path = os.path.dirname(os.path.dirname(__file__))
            
        parent_path = os.path.dirname(base_module_path)
        #impl_path = os.path.join(parent_path, 'd21_multimoneda_impl')
        impl_path = parent_path
        
        # Create base implemention directory
        os.makedirs(impl_path, exist_ok=True)
        
        # 2. Get target currencies
        if not CURRENCIES or len(CURRENCIES) < 2:
            _logger.error("No hay suficientes monedas configuradas para generar el módulo secundario.")
            return
            
        target_ccs = [c.lower() for c in CURRENCIES[1:]]
        
        # Pre-fetch currency symbols
        currency_records = self.env['res.currency'].search([('name', 'in', [c.upper() for c in CURRENCIES])])
        cc_to_symbol = {c.name.lower(): c.symbol for c in currency_records}
        
        # 3. Scan models and group by module
        # Structure: modules_data[module_name][model_name] = [fields]
        modules_data = {}
        target_field_keywords = MONETARY_KEYWORDS
        
        # Pre-fetch all ir.model.fields and their corresponding ir.model.data
        # to know which module DEFINED each field (the external ID module)
        # Use localized context to get the correct field descriptions
        all_fields = self.env['ir.model.fields'].with_context(lang=LANG).search([('model', 'not like', 'd21_%')])
        
        # Get external ID info for these fields
        model_data = self.env['ir.model.data'].search_read(
            [('model', '=', 'ir.model.fields'), ('res_id', 'in', all_fields.ids)],
            ['res_id', 'module']
        )
        res_id_to_module = {d['res_id']: d['module'] for d in model_data}

        field_info_map = {}
        for f in all_fields:
            # Use the module from ir.model.data (external id) if available,
            # fallback to the first module in the list if not (standard fallback)
            module = res_id_to_module.get(f.id) or (f.modules.split(',')[0] if f.modules else 'base')
            field_info_map[(f.model, f.name)] = {
                'module': module,
                'string': f.field_description or f.name
            }

        # We iterate over the registry to find models with monetary or float fields
        for model_name, model_class in self.env.registry.items():
            if model_name.startswith('d21_'):
                continue
            
            # Use the model from the environment to get fields correctly
            try:
                model = self.env[model_name]
            except:
                continue
            
            # Determine Odoo base type
            if model._abstract:
                base_type = 'models.AbstractModel'
            elif model._transient:
                base_type = 'models.TransientModel'
            else:
                base_type = 'models.Model'
            
            for field_name, field in model._fields.items():
                is_monetary = field.type == 'monetary'
                is_float_monetary = field.type == 'float' and any(kw in field_name.lower() for kw in target_field_keywords)
                
                if (is_monetary or is_float_monetary) and not field_name.startswith('d21_'):
                    # Get original module and localized string
                    info = field_info_map.get((model_name, field_name), {})
                    orig_module = info.get('module', 'base')
                    field_string = info.get('string', field_name)
                    
                    if orig_module not in modules_data:
                        modules_data[orig_module] = {}
                    
                    if model_name not in modules_data[orig_module]:
                        modules_data[orig_module][model_name] = {
                            'base_type': base_type,
                            'fields': []
                        }
                        
                    modules_data[orig_module][model_name]['fields'].append((field_name, field.readonly, field_string))

        # 4. Generate Odoo modules
        for orig_module, models_to_extend in modules_data.items():
            package_name = f"d21_multimoneda__{orig_module}"
            module_dir = os.path.join(impl_path, package_name)
            models_dir = os.path.join(module_dir, 'models')
            
            os.makedirs(models_dir, exist_ok=True)
            
            # Generate Python code for each model
            for model_name, model_info in models_to_extend.items():
                fields_list = model_info['fields']
                base_type = model_info['base_type']
                
                model_file_base = model_name.replace('.', '_')
                model_class_name = model_file_base.title().replace('_', '')
                # License as single-line comments at the top
                license_header = [f"# {line}".strip() if line.strip() else "#" for line in LICENSE]
                
                file_content = license_header + [
                    "",
                    "\n".join(AUTOGENERATED_WARNING),
                    "",
                    "from odoo import models, fields, api",
                    "",
                    "",
                    f"class {model_class_name}({base_type}):",
                    f"    _inherit = '{model_name}'",
                    ""
                ]
                
                for cc in target_ccs:
                    cc_upper = cc.upper()
                    cc_symbol = cc_to_symbol.get(cc, cc_upper)
                    
                    # Currency many2one
                    file_content.append(f"    d21_moneda_{cc} = fields.Many2one(")
                    file_content.append(f"        'res.currency', ")
                    file_content.append(f"        string='Moneda {cc_upper}', ")
                    file_content.append(f"        default=lambda self: self.env.ref('base.{cc_upper}').id,")
                    file_content.append(f"        store=True")
                    file_content.append(f"    )")
                    
                    # Rate field
                    file_content.append(f"    d21_tasa_{cc} = fields.Monetary(")
                    file_content.append(f"        string='Tasa de cambio {cc_symbol}', ")
                    file_content.append(f"        currency_field='d21_moneda_{cc}', ")
                    file_content.append(f"        default=1.0,")
                    file_content.append(f"        store=True,")
                    file_content.append(f"    )")
                    file_content.append("")
                    
                    for field_name, readonly, field_string in fields_list:
                        conv_field = f"d21_{field_name}_{cc}"
                        compute_name = f"_compute_{conv_field}"
                        inverse_name = f"_inverse_{conv_field}"
                        
                        # Field string with currency symbol
                        localized_string = f"{field_string} {cc_symbol}"
                        
                        # Compute method
                        file_content.append(f"    @api.depends('{field_name}', 'd21_tasa_{cc}')")
                        file_content.append(f"    def {compute_name}(self):")
                        file_content.append(f"        for record in self:")
                        file_content.append(f"            record.{conv_field} = record.{field_name} * record.d21_tasa_{cc}")
                        file_content.append("")
                        
                        # Inverse method if not readonly
                        inv_attr = ""
                        if not readonly:
                            file_content.append(f"    def {inverse_name}(self):")
                            file_content.append(f"        for record in self:")
                            file_content.append(f"            if record.d21_tasa_{cc}:")
                            file_content.append(f"                record.{field_name} = record.{conv_field} / record.d21_tasa_{cc}")
                            file_content.append("")
                            inv_attr = f",\n        inverse='{inverse_name}'"
                        
                        # Field definition
                        file_content.append(f"    {conv_field} = fields.Monetary(")
                        file_content.append(f"        string='{localized_string}',")
                        file_content.append(f"        currency_field='d21_moneda_{cc}',")
                        file_content.append(f"        compute='{compute_name}',")
                        file_content.append(f"        store=True,")
                        file_content.append(f"        group_operator='sum'{inv_attr}")
                        file_content.append(f"    )")
                        file_content.append("")

                # Write model file
                with open(os.path.join(models_dir, f"{model_file_base}.py"), 'w', encoding='utf-8') as f:
                    f.write("\n".join(file_content))

            # License header helper for multi-line strings
            license_as_comment = "\n".join([f"# {line}".strip() if line.strip() else "#" for line in LICENSE])

            # 5. Generate __init__.py for models
            with open(os.path.join(models_dir, '__init__.py'), 'w', encoding='utf-8') as f:
                f.write(f"{license_as_comment}\n\n")
                f.write("\n".join(AUTOGENERATED_WARNING))
                f.write("\n\n")
                for model_name in models_to_extend:
                    f.write(f"from . import {model_name.replace('.', '_')}\n")
            
            # 6. Generate __init__.py for module
            with open(os.path.join(module_dir, '__init__.py'), 'w', encoding='utf-8') as f:
                f.write(f"{license_as_comment}\n\n")
                f.write("\n".join(AUTOGENERATED_WARNING))
                f.write("\n\n")
                f.write("from . import models\n")
            
            # 6.1 Generate LICENSE and COPYRIGHT files
            with open(os.path.join(module_dir, 'LICENSE'), 'w', encoding='utf-8') as f:
                f.write("\n".join(LICENSE))
            
            with open(os.path.join(module_dir, 'COPYRIGHT'), 'w', encoding='utf-8') as f:
                f.write("\n".join(COPYRIGHT))
                
            # 7. Generate __manifest__.py
            manifest_content = f"""{{
    'name': 'DIMAC21 Multi-Moneda ({orig_module})',
    'version': '18.0.1.0.0',
    'summary': 'Módulo generado automáticamente para manejar conversiones multi-moneda en `{orig_module}`',
    'depends': ['{orig_module}', 'd21_multimoneda'],
    'installable': True,
    'auto_install': True,
    'license': 'OPL-1',
}}"""
            with open(os.path.join(module_dir, '__manifest__.py'), 'w', encoding='utf-8') as f:
                f.write(f"{license_as_comment}\n\n")
                f.write("\n".join(AUTOGENERATED_WARNING))
                f.write("\n\n")
                f.write(manifest_content)
            
            _logger.info("Módulo `%s` generado exitosamente en %s", package_name, module_dir)

        _logger.info("Todos los módulos multi-moneda generados exitosamente en %s", impl_path)
